### ISSUE TITLE
Stack dump on reply

### ISSUE THREAD

**Issue by kentonv** [jparyani/wave#1]
Steps to repro:
1. Create a new Wave.
2. Delete the welcome bot message.
3. Click on the "reply" box.

Token:  1408140846109
 Exception caught: (TypeError) 
 __gwt$exception: <skipped>: Cannot read property 'c' of undefined
  Unknown.si (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@7490:??)
  Unknown.ri (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@41:??)
  Unknown.xi (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@21:??)
  Unknown.Bi (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@21:??)
  Unknown.dx (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@19:??)
  Unknown.gx (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@19:??)
  Unknown.Hw (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@110:??)
  Unknown.xUb (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@31:??)
  Unknown.Tt (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@144:??)
  Unknown.zUb (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@121:??)
  Unknown.JUb (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@19160:??)
  Unknown.RNb (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@92:??)
  Unknown.gQb (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@73:??)
  Unknown.Cj (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@29:??)
  Unknown.Gj (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@57:??)
  Unknown.<anonymous> (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@54:??)
Caused by: Token:  1408140846111
 (TypeError) 
 __gwt$exception: <skipped>: Cannot read property 'c' of undefined
  Unknown.eLe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@37:??)
  Unknown.PVe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@10304:??)
  Unknown.rUe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@64:??)
  Unknown.tUe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@124:??)
  Unknown.sUe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@37:??)
  Unknown.pNe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@33:??)
  Unknown.mNe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@87:??)
  Unknown.fVe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@8854:??)
  Unknown.OLe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@28805:??)
  Unknown.vLe (http://p9iiy51osg9zxta87j37.local.sandstorm.io:2080/webclient/D7C21D7B2FA19B5E40509404B44B77CF.cache.html@100:??)

**Comment by kentonv** [comment]
Also the "refresh" link in the error message goes to a blank page, apparently because it is missing the document ID fragment.

Similarly, clicking the Wave icon in the upper-left has the same problem.

**Comment by jparyani** [comment]
This is a bug up-stream with Wave, that you can't delete the root wavelet in a wave.

I've made a few changes that make this less of a problem.
- The wave and root wavelet is now owned by the user instead of the bot
- The root wavelet's message is a bit more clear, and asks for the user to edit the wavelet instead of deleting it
- The refresh button will now refresh the current page. I've removed the link from the wave icon
